name: Bump Pluto Version

on:
  repository_dispatch:
    types: [trigger-bump-pluto]
  workflow_dispatch:
    inputs:
      publishedPackages:
        description: "The published packages to bump"
        required: true
        default: '[{"name": "@plutolang/cli", "version": "0.4.0"}]'

jobs:
  bump_pluto:
    name: Bump Pluto packages version and Push a Commit
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Output the event payload
        run: echo "$CLIENT_PAYLOAD"
        env:
          CLIENT_PAYLOAD: ${{ toJSON(github.event.client_payload) }}

      - name: Run Bump Script
        run: node scripts/bump-pluto.js "$PACKAGES"
        env:
          PACKAGES: ${{ toJSON(github.event.client_payload.packages) || inputs.publishedPackages }}

      - name: Exit if no updates
        # `git diff-index --quiet HEAD --` will return a 1 if there are any updates.
        run: |
          if git diff --quiet; then
            echo "No updates."
            echo "NO_UPDATE=true" >> $GITHUB_ENV
          else
            git diff --name-only
          fi

      - name: Commit changes
        if: env.NO_UPDATE != 'true'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "feat: bump pluto packages to the latest versions" -m "Bump the Pluto packages to the latest version. See details in [workflow run].
          [Workflow Run]: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          ------
          *Automatically created via the 'bump-pluto' workflow*"

      - name: Push changes
        if: env.NO_UPDATE != 'true'
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
